extends SceneTree
const S=preload("res://game/scripts/journey_state.gd")
func _initialize()->void:
 var s=S.new()
 assert(not s.onboarded and s.level==1 and s.cards==0)
 assert(not s.choose_difficulty("invalid"))
 assert(s.choose_difficulty("hard") and s.difficulty=="hard")
 assert(not s.complete_task("delivery"))
 assert(not s.can_test("vocabulary"))
 s.study("vocabulary")
 assert(s.can_test("vocabulary"))
 assert(s.complete_task("vocabulary"))
 assert(not s.complete_task("vocabulary"))
 s.complete_task("reading")
 assert(s.level==1 and s.level_points()==2)
 s.complete_task("harvest")
 assert(s.level==2 and s.level_points()==0)
 assert(not s.deposit(1))
 s.complete_task("delivery");s.complete_task("grammar");s.complete_task("letter")
 assert(s.level==3)
 s.cards=10
 assert(not s.deposit(-1))
 assert(s.deposit(5) and s.bank_balance==5 and s.cards==5)
 assert(not s.withdraw(6))
 assert(s.withdraw(3) and s.cards==8 and s.bank_balance==2)
 assert(not s.catch_fish(false))
 assert(s.catch_fish(true) and s.fish==1)
 assert(not s.catch_fish(true))
 s.wood=5;s.cards=10
 assert(s.improve_home())
 assert(not s.improve_home())
 assert(s.level==4)
 assert(s.expand_orchard())
 assert(s.buy_outfit())
 s.cards=10
 assert(s.buy_power())
 assert(s.level==5)
 var p="user://test_journey.json"
 s.onboarded=true;s.letter_draft="My saved letter"
 assert(s.save_to(p))
 var t=S.new();assert(t.load_from(p))
 assert(t.level==5 and t.onboarded and t.bank_balance==2 and t.letter_draft==s.letter_draft)
 DirAccess.remove_absolute(p)
 print("JOURNEY_STATE_PASSED");quit()
